.gitignore, imports/startup/server/index.js, imports/ui/components/address/address.html, imports/ui/components/block/block.html, imports/ui/components/block/block.js, imports/ui/components/lastblocks/lastblocks.html, imports/ui/components/lastblocks/lastblocks.js, imports/ui/components/lasttx/lasttx.html, imports/ui/components/lasttx/lasttx.js, imports/ui/components/status/status.html, imports/ui/components/status/status.js, imports/ui/components/tx/tx.html, imports/ui/components/tx/tx.js, imports/ui/layouts/body/body.html, imports/ui/layouts/body/sidebar.html, package-lock.json, package.json
- epoch is not necessary anymore
- search for blocks
- show blocks
- block headerhash in homepage
- block height
- node sync status is not shown
- nodes count (double connection)
- latest transactions is empty
- show transactions / last transactions
- etc, etc
=> grpc API - Fixes+updates

imports/ui/components/tx/tx.js
=> Adding missing call to status

imports/ui/components/tx/tx.html, imports/ui/components/tx/tx.js
* Fixes reactive routing of transactions to fix #41 
* "Not found" tx hashes are displayed in a more user accessible style
=> Tx display fixes

imports/startup/client/routes.js, imports/ui/components/address/address.js
First stage of massively improving the usability of addresses with large numbers of transactions in them (e.g. for Testnet as a demo: Q010300082382a52f8ba9c2d33ad807c2cdd5bd086c2c2fe63c6ea13b630d1280894c3a39e1c380)
=> Improved pagination with Routes to specific pages

imports/ui/components/address/address.html, imports/ui/components/address/address.js, imports/ui/layouts/body/body.html, imports/ui/layouts/body/body.js, imports/ui/stylesheets/overrides.css
=> Add a quick way of jumping between many pages

imports/ui/components/address/address.js
This fixes the UI glitches @cyyber has reported and should prevent the deployment alerts of page request failure we have been receiving recently: the infinite loop, when triggered, causes the API to be throttled and subsequent failure.
=> Fixes occassional infinite loop bug is addresses

imports/startup/client/index.js, imports/ui/layouts/body/body.html, imports/ui/layouts/body/body.js, imports/ui/stylesheets/overrides.css
Should help prevent idle clients
=> Add disconnection timeouts for clients

client/head.html, imports/ui/components/address/address.html, imports/ui/components/address/address.js, imports/ui/stylesheets/overrides.css
=> Identicon support in address page

.meteor/packages, .meteor/versions, imports/startup/server/index.js
adds support for the following headers:
X-XSS-Protection
Strict-Transport-Security
=> use QRL version of browser-policy

imports/ui/components/lasttx/lasttx.html, imports/ui/components/lasttx/lasttx.js, imports/ui/stylesheets/overrides.css
=> LastTx UI and UX improvements desktop/mobile

imports/ui/components/lasttx/lasttx.html, imports/ui/components/lasttx/lasttx.js, imports/ui/stylesheets/overrides.css
=>  LastTx UI and UX improvements desktop/mobile

.meteor/packages, .meteor/versions, imports/ui/components/status/status.js, package-lock.json
* Updates to master (#134)
* Default to new Testnet infrastructure
* Indentation
* Updating cron to get block time and std dev
* Uptime bug fix
=> Uptime bug fix (#135)

imports/ui/components/lastblocks/lastblocks.html, imports/ui/stylesheets/overrides.css, package-lock.json
* Regular package security audit
* UI glitch fix for “mined by” line (fixes #158)
=> Fixes "Mined by..." line UI glitch (#157)

imports/ui/components/lastblocks/lastblocks.html, imports/ui/stylesheets/overrides.css, package-lock.json
* Regular package security audit
* UI glitch fix for “mined by” line (fixes #158)
=> Fixes "Mined by..." line UI glitch (#157) (#159)

imports/startup/client/mining-pools.js
=> Add New Pool

.meteor/packages, .meteor/versions, imports/startup/both/index.js, imports/startup/client/index.js, imports/startup/server/index.js, imports/ui/components/address/address.js, imports/ui/components/block/block.js, imports/ui/components/lastblocks/lastblocks.js, imports/ui/components/tx/tx.js, imports/ui/stylesheets/overrides.css
=> Add JSON API endpoints for address/block/tx

imports/startup/server/index.js, imports/ui/components/address/address.js, imports/ui/components/lasttx/lasttx.js, imports/ui/components/tx/tx.html, imports/ui/stylesheets/overrides.css
- Fix bad caching of unconfirmed Tx
- Remove console debugging lasttx
- Fix console errors and routing in address page
- Further dark theme visual tweaks
- Cleaner labels
=> Cache and visual updates

public/dark.css, public/light.css
=> Fix search box on mobile

client/test-methods.js, imports/client/ui/search.js, imports/client/ui/tokens.html, imports/client/ui/tokens.js, package-lock.json, package.json, server/index.js
methods for richlist and total addresses in addition to full token search by text functionality
=> Add token search by text and some new methods

imports/ui/components/lasttx/lasttx.html, imports/ui/components/lasttx/lasttx.js, imports/ui/components/lastunconfirmedtx/lastunconfirmedtx.html, imports/ui/components/lastunconfirmedtx/lastunconfirmedtx.js, package-lock.json
Currently Keybase transactions do not appear correctly in the lasttxn and unconfirmed transaction views. This PR resolves the issue.
=> Show keybase transactions in lasttx and unconfirmed tx views

imports/ui/components/address/address.html, imports/ui/components/address/address.js, imports/ui/components/lasttx/lasttx.html, imports/ui/components/lasttx/lasttx.js, imports/ui/components/tx/tx.html, imports/ui/components/tx/tx.js
=> Adds multi_sig_create transaction type

imports/startup/server/index.js, imports/ui/components/address/address.js
=> fix: token balances in address page

imports/startup/server/index.js, imports/ui/components/address/address.html, imports/ui/components/address/address.js, imports/ui/components/search/search.js
This PR adds links to all slaves from a master address page.
There's also a better fix (read: less glitchy) for #319
=> Slave view
